%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.0

-ifndef(emqx_gpb).
-define(emqx_gpb, true).

-define(emqx_gpb_gpb_version, "4.10.0").

-ifndef('EMQXPRESENCE_PB_H').
-define('EMQXPRESENCE_PB_H', true).
-record('EmqxPresence',
        {username               :: iodata() | undefined, % = 1
         client_id              :: iodata() | undefined, % = 2
         time                   :: integer() | undefined, % = 3, 32 bits
         presence               :: {connected_message, emqx_gpb:'ConnectedMessage'()} | {disconnected_message, emqx_gpb:'DisconnectedMessage'()} | undefined % oneof
        }).
-endif.

-ifndef('CONNECTEDMESSAGE_PB_H').
-define('CONNECTEDMESSAGE_PB_H', true).
-record('ConnectedMessage',
        {ip_address             :: iodata() | undefined, % = 1
         conn_ack               :: 'CONNACK_ACCEPT' | 'CONNACK_PROTO_VER' | 'CONNACK_INVALID_ID' | 'CONNACK_SERVER' | 'CONNACK_CREDENTIALS' | 'CONNACK_AUTH' | integer() | undefined, % = 2, enum ConnectedMessage.ConnAck
         session                :: boolean() | 0 | 1 | undefined, % = 3
         protocol_version       :: integer() | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('DISCONNECTEDMESSAGE_PB_H').
-define('DISCONNECTEDMESSAGE_PB_H', true).
-record('DisconnectedMessage',
        {reason                 :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('EMQXMESSAGE_PB_H').
-define('EMQXMESSAGE_PB_H', true).
-record('EmqxMessage',
        {username               :: iodata() | undefined, % = 1
         client_id              :: iodata() | undefined, % = 2
         topic                  :: iodata() | undefined, % = 3
         qos                    :: integer() | undefined, % = 4, 32 bits
         retain                 :: boolean() | 0 | 1 | undefined, % = 5
         dup                    :: boolean() | 0 | 1 | undefined, % = 6
         id                     :: integer() | undefined, % = 7, 32 bits
         payload                :: iodata() | undefined % = 8
        }).
-endif.

-endif.
